"""EU4 이벤트 픽처 키 목록 (한글 카테고리 라벨 포함).

게임 본체 interface/eventpictures.gfx 의 spriteType 들을 기반으로 함.
이벤트 픽처는 모두 512x132 DDS 가 표준.
사용자가 어떤 키를 선택하면, 같은 키로 모드에서 덮어써서 게임 내 이벤트 픽처를
교체합니다.
"""

EVENT_PICTURE_SIZE = (512, 132)

# 카테고리 한글 라벨 (폴더 → 한글)
CATEGORY_LABELS = {
    "event_pictures_EUROPEAN": "유럽 (기본)",
    "event_pictures_estates": "신분 (Estates)",
    "event_pictures_AOW": "전쟁의 기술 DLC",
    "event_pictures_ep": "오세아니아 / 폴리네시아",
    "event_pictures_leviathan": "리바이어던 DLC",
    "event_pictures_poland": "동방 / 폴란드 / 유목민",
    "event_pictures_king_of_kings": "왕중왕 DLC",
    "event_pictures_winds_of_change": "변화의 바람 DLC",
}

# 자주 쓰는 키에 대한 한글 별칭 (없으면 영문 키 그대로 표시)
KOREAN_ALIASES = {
    "BATTLE_eventPicture": "전투",
    "SIEGE_eventPicture": "공성전",
    "COURT_eventPicture": "궁정",
    "ADVISOR_eventPicture": "고문관",
    "ACCUSATION_eventPicture": "고발/탄핵",
    "ANGRY_MOB_eventPicture": "성난 군중",
    "ARTWORK_eventPicture": "예술 작품",
    "ASSASSINATION_eventPicture": "암살",
    "BAD_WITH_MONARCH_eventPicture": "군주와의 갈등",
    "GOOD_WITH_MONARCH_eventPicture": "군주와의 우호",
    "BANKRUPTCY_eventPicture": "파산",
    "BARBARY_PIRATES_eventPicture": "바르바리 해적",
    "BIG_BOOK_eventPicture": "큰 책 (학문)",
    "BUDDHA_eventPicture": "불상",
    "BORDER_TENSION_eventPicture": "국경 긴장",
    "CITY_DEVELOPMENT_eventPicture": "도시 발전",
    "CITY_VIEW_eventPicture": "도시 전경",
    "CIVIL_WAR_eventPicture": "내전",
    "COLONIZATION_eventPicture": "식민화",
    "COMET_SIGHTED_eventPicture": "혜성 출현",
    "CONQUEST_eventPicture": "정복",
    "CORRUPTION_eventPicture": "부패",
    "COUNTRY_COLLAPSE_eventPicture": "국가 붕괴",
    "CULTURE_eventPicture": "문화",
    "DEATH_OF_HEIR_eventPicture": "후계자 사망",
    "DEBATE_REPUBLICAN_eventPicture": "공화정 토론",
    "DIPLOMACY_eventPicture": "외교",
    "ECONOMY_eventPicture": "경제",
    "ELECTION_REPUBLICAN_eventPicture": "공화정 선거",
    "EXPLORERS_eventPicture": "탐험가",
    "FAMINE_eventPicture": "기근",
    "FARMING_eventPicture": "농경",
    "FEAST_eventPicture": "연회",
    "FORT_eventPicture": "요새",
    "GREAT_BUILDING_eventPicture": "위대한 건축",
    "HARBOUR_eventPicture": "항구",
    "HORDE_ON_HORSEBACK_eventPicture": "기마 유목민",
    "HRE_eventPicture": "신성 로마 제국",
    "IMPORTANT_STATUE_eventPicture": "동상/조각",
    "INVENTION_eventPicture": "발명",
    "KING_SICK_IN_BED_eventPicture": "병상의 왕",
    "LAND_MILITARY_eventPicture": "육군",
    "NAVAL_MILITARY_eventPicture": "해군",
    "LIBERUM_VETO_eventPicture": "자유거부권",
    "MERCHANTS_TALKING_eventPicture": "상인 회의",
    "MILITARY_CAMP_eventPicture": "군영",
    "NATIVES_eventPicture": "원주민",
    "NEW_HEIR_eventPicture": "새 후계자",
    "ORTHODOX_eventPicture": "정교회",
    "OVEREXTENSION_eventPicture": "과도확장",
    "PAINTER_ARTIST_eventPicture": "화가/예술가",
    "PLAGUE_eventPicture": "역병",
    "POPE_PREACHING_eventPicture": "교황 설교",
    "PRAYING_eventPicture": "기도",
    "REFORM_eventPicture": "개혁",
    "RELIGION_eventPicture": "종교",
    "RELIGIOUS_CONVERSION_eventPicture": "종교 개종",
    "RELIGIOUS_TURMOIL_eventPicture": "종교 분쟁",
    "RELIGIOUS_WARS_eventPicture": "종교 전쟁",
    "REVOLUTION_eventPicture": "혁명",
    "SHIP_SAILING_eventPicture": "항해",
    "SPY_eventPicture": "첩자",
    "ST_PETERS_CHURCH_eventPicture": "성 베드로 대성당",
    "STREET_SPEECH_eventPicture": "거리 연설",
    "THEATRE_eventPicture": "극장",
    "TOURNAMENT_eventPicture": "마상시합",
    "TRADEGOODS_eventPicture": "교역품",
    "TRADE_GOODS_FURS_FISH_AND_SALT_eventPicture": "교역품: 모피·생선·소금",
    "TRADE_GOODS_METALS_AND_MINING_EQUIPENT_eventPicture": "교역품: 금속·광산",
    "TRADE_GOODS_PLANTATION_GOODS_IN_WAREHOUSE_eventPicture": "교역품: 플랜테이션",
    "UNIVERSITY_eventPicture": "대학",
    "WAR_OF_THE_ROSES_eventPicture": "장미 전쟁",
    "WESTERNISATION_eventPicture": "서구화",
    "WOUNDED_SOLDIERS_eventPicture": "부상병",
    "REFORM_eventPicture": "개혁",
    "NOBLE_ESTATE_eventPicture": "귀족 신분",
    "NOBLE_ESTATE_DEMANDS_eventPicture": "귀족 신분 요구",
    "NOBLE_ESTATE_TAKE_OVER_eventPicture": "귀족 신분 권력 장악",
    "BURGHER_ESTATE_eventPicture": "시민 신분",
    "BURGHER_ESTATE_UPSET_eventPicture": "시민 신분 분노",
    "CHURCH_ESTATE_1_eventPicture": "성직자 신분 1",
    "CHURCH_ESTATE_2_eventPicture": "성직자 신분 2",
    "CHURCH_ESTATE_UPSET_eventPicture": "성직자 신분 분노",
    "AULIC_COUNCIL_eventPicture": "궁정 회의",
    "CATHOLIC_RULERS_PRAYING_eventPicture": "가톨릭 군주 기도",
    "DEFENESTRATION_PRAGUE_eventPicture": "프라하 창밖 투척 사건",
    "DIPLOMACY_SIGNING_eventPicture": "외교 조인",
    "FARMING_WIFE_eventPicture": "농촌의 아내",
    "GENERALS_DISCUSSING_eventPicture": "장군들의 회의",
    "PEASANTS_BARTERING_eventPicture": "농민의 물물교환",
    "PRINCE_BISHOP_RESIGN_eventPicture": "주교후 사임",
    "PROTESTANT_CATHOLIC_DEBATE_eventPicture": "신·구교 토론",
    "REVOLT_HUNGARIAN_eventPicture": "헝가리 반란",
    "SCOTTISH_MERCENARIES_eventPicture": "스코틀랜드 용병",
    "SIEGE_PRAGUE_CASTLE_eventPicture": "프라하성 공성전",
    "SOLDIERS_FREEZING_eventPicture": "동사하는 병사",
    "VILLAGE_BURNING_eventPicture": "마을 방화",
    "VILLAGE_RAIDED_eventPicture": "마을 약탈",
    "SEJM_eventPicture": "세임 (폴란드 의회)",
    "HUSSARS_eventPicture": "후사르",
    "BATTLE_VISTULA_LAGOON_eventPicture": "비스와 석호 해전",
    "IMPALED_SOLDIERS_eventPicture": "처형된 병사",
    "MONGOL_BANNERS_eventPicture": "몽골 깃발",
    "SYNTHETICS_eventPicture": "직물",
    "EP_ISLAND_eventPicture": "남태평양 섬",
    "EP_POLYNESIAN_MARAE_eventPicture": "폴리네시아 마라에",
    "EP_MOAIS_eventPicture": "모아이",
    "EP_MAORI_HAKA_eventPicture": "마오리 하카",
    "EP_MANIHOLE_HELMET_eventPicture": "폴리네시아 투구",
    "EP_POLYNESIAN_DANCES_eventPicture": "폴리네시아 무용",
    "EP_POLYNESIAN_HORN_eventPicture": "폴리네시아 뿔피리",
    "EP_POLYNESIAN_SHIPS_eventPicture": "폴리네시아 선박",
    "EP_POLYNESIAN_TATTOO_eventPicture": "폴리네시아 문신",
    "EP_SAMOAN_WARRIORS_eventPicture": "사모아 전사",
    "NUSANTARA_QUEEN_eventPicture": "누산타라 여왕",
    "MALAYAN_PORT_eventPicture": "말레이 항구",
    "NUSANTARA_THRONE_eventPicture": "누산타라 왕좌",
    "NUSANTARA_WAR_eventPicture": "누산타라 전쟁",
    "SHWEDAGON_PAGON_eventPicture": "쉐다곤 파고다",
    "CONSTANTINOPLE_eventPicture": "콘스탄티노폴리스",
    "GHULAMS_ESTATE_eventPicture": "굴람 신분",
    "GHULAMS_ESTATE_DEMANDS_eventPicture": "굴람 신분 요구",
    "QIZILBASH_ESTATE_eventPicture": "키질바시 신분",
    "QIZILBASH_ESTATE_DEMANDS_eventPicture": "키질바시 신분 요구",
    "JURAJ_JANOSIK_eventPicture": "유라이 야노시크",
}

# 게임 본체 이벤트 픽처 정의: (sprite_name, vanilla_folder)
# 사용자 GUI 에는 이걸로 목록을 보여주고 카테고리별 묶음.
EVENT_PICTURES = [
    ("TRADE_GOODS_FURS_FISH_AND_SALT_eventPicture", "event_pictures_EUROPEAN"),
    ("TRADE_GOODS_METALS_AND_MINING_EQUIPENT_eventPicture", "event_pictures_EUROPEAN"),
    ("TRADE_GOODS_PLANTATION_GOODS_IN_WAREHOUSE_eventPicture", "event_pictures_EUROPEAN"),
    ("NOBLE_ESTATE_DEMANDS_eventPicture", "event_pictures_estates"),
    ("NOBLE_ESTATE_eventPicture", "event_pictures_estates"),
    ("NOBLE_ESTATE_TAKE_OVER_eventPicture", "event_pictures_estates"),
    ("BURGHER_ESTATE_eventPicture", "event_pictures_estates"),
    ("BURGHER_ESTATE_UPSET_eventPicture", "event_pictures_estates"),
    ("CHURCH_ESTATE_1_eventPicture", "event_pictures_estates"),
    ("CHURCH_ESTATE_2_eventPicture", "event_pictures_estates"),
    ("CHURCH_ESTATE_UPSET_eventPicture", "event_pictures_estates"),
    ("SYNTHETICS_eventPicture", "event_pictures_poland"),
    ("easterngfx_WOUNDED_SOLDIERS_eventPicture", "event_pictures_poland"),
    ("easterngfx_COUNTRY_COLLAPSE_eventPicture", "event_pictures_poland"),
    ("easterngfx_NAVAL_MILITARY_eventPicture", "event_pictures_poland"),
    ("easterngfx_LAND_MILITARY_eventPicture", "event_pictures_poland"),
    ("easterngfx_MILITARY_CAMP_eventPicture", "event_pictures_poland"),
    ("altaic_MILITARY_CAMP_eventPicture", "event_pictures_poland"),
    ("tartar_MILITARY_CAMP_eventPicture", "event_pictures_poland"),
    ("altaic_LAND_MILITARY_eventPicture", "event_pictures_poland"),
    ("tartar_LAND_MILITARY_eventPicture", "event_pictures_poland"),
    ("altaic_TOURNAMENT_eventPicture_eventPicture", "event_pictures_poland"),
    ("tartar_TOURNAMENT_eventPicture_eventPicture", "event_pictures_poland"),
    ("easterngfx_COURT_eventPicture", "event_pictures_poland"),
    ("easterngfx_LIBERUM_VETO_eventPicture", "event_pictures_poland"),
    ("easterngfx_DEBATE_REPUBLICAN_eventPicture", "event_pictures_poland"),
    ("BATTLE_VISTULA_LAGOON_eventPicture", "event_pictures_poland"),
    ("HUSSARS_eventPicture", "event_pictures_poland"),
    ("IMPALED_SOLDIERS_eventPicture", "event_pictures_poland"),
    ("SEJM_eventPicture", "event_pictures_poland"),
    ("MONGOL_BANNERS_eventPicture", "event_pictures_poland"),
    ("ACCUSATION_eventPicture", "event_pictures_EUROPEAN"),
    ("ADVISOR_eventPicture", "event_pictures_EUROPEAN"),
    ("ANGRY_MOB_eventPicture", "event_pictures_EUROPEAN"),
    ("ARTWORK_eventPicture", "event_pictures_EUROPEAN"),
    ("ASSASSINATION_eventPicture", "event_pictures_EUROPEAN"),
    ("BAD_WITH_MONARCH_eventPicture", "event_pictures_EUROPEAN"),
    ("BANKRUPTCY_eventPicture", "event_pictures_EUROPEAN"),
    ("BATTLE_eventPicture", "event_pictures_EUROPEAN"),
    ("BORDER_TENSION_eventPicture", "event_pictures_EUROPEAN"),
    ("BIG_BOOK_eventPicture", "event_pictures_EUROPEAN"),
    ("BUDDHA_eventPicture", "event_pictures_EUROPEAN"),
    ("CITY_DEVELOPMENT_eventPicture", "event_pictures_EUROPEAN"),
    ("CITY_VIEW_eventPicture", "event_pictures_EUROPEAN"),
    ("CIVIL_WAR_eventPicture", "event_pictures_EUROPEAN"),
    ("COLONIZATION_eventPicture", "event_pictures_EUROPEAN"),
    ("COMET_SIGHTED_eventPicture", "event_pictures_EUROPEAN"),
    ("CONQUEST_eventPicture", "event_pictures_EUROPEAN"),
    ("CORRUPTION_eventPicture", "event_pictures_EUROPEAN"),
    ("COUNTRY_COLLAPSE_eventPicture", "event_pictures_EUROPEAN"),
    ("COURT_eventPicture", "event_pictures_EUROPEAN"),
    ("CULTURE_eventPicture", "event_pictures_EUROPEAN"),
    ("DEATH_OF_HEIR_eventPicture", "event_pictures_EUROPEAN"),
    ("DEBATE_REPUBLICAN_eventPicture", "event_pictures_EUROPEAN"),
    ("DIPLOMACY_eventPicture", "event_pictures_EUROPEAN"),
    ("ECONOMY_eventPicture", "event_pictures_EUROPEAN"),
    ("ELECTION_REPUBLICAN_eventPicture", "event_pictures_EUROPEAN"),
    ("EXPLORERS_eventPicture", "event_pictures_EUROPEAN"),
    ("FAMINE_eventPicture", "event_pictures_EUROPEAN"),
    ("FARMING_eventPicture", "event_pictures_EUROPEAN"),
    ("FEAST_eventPicture", "event_pictures_EUROPEAN"),
    ("FORT_eventPicture", "event_pictures_EUROPEAN"),
    ("GOOD_WITH_MONARCH_eventPicture", "event_pictures_EUROPEAN"),
    ("GREAT_BUILDING_eventPicture", "event_pictures_EUROPEAN"),
    ("HARBOUR_eventPicture", "event_pictures_EUROPEAN"),
    ("HORDE_ON_HORSEBACK_eventPicture", "event_pictures_EUROPEAN"),
    ("HRE_eventPicture", "event_pictures_EUROPEAN"),
    ("IMPORTANT_STATUE_eventPicture", "event_pictures_EUROPEAN"),
    ("INVENTION_eventPicture", "event_pictures_EUROPEAN"),
    ("KING_SICK_IN_BED_eventPicture", "event_pictures_EUROPEAN"),
    ("LAND_MILITARY_eventPicture", "event_pictures_EUROPEAN"),
    ("LIBERUM_VETO_eventPicture", "event_pictures_EUROPEAN"),
    ("MERCHANTS_TALKING_eventPicture", "event_pictures_EUROPEAN"),
    ("MILITARY_CAMP_eventPicture", "event_pictures_EUROPEAN"),
    ("NATIVES_eventPicture", "event_pictures_EUROPEAN"),
    ("NAVAL_MILITARY_eventPicture", "event_pictures_EUROPEAN"),
    ("NEW_HEIR_eventPicture", "event_pictures_EUROPEAN"),
    ("ORTHODOX_eventPicture", "event_pictures_EUROPEAN"),
    ("OVEREXTENSION_eventPicture", "event_pictures_EUROPEAN"),
    ("PAINTER_ARTIST_eventPicture", "event_pictures_EUROPEAN"),
    ("PLAGUE_eventPicture", "event_pictures_EUROPEAN"),
    ("POPE_PREACHING_eventPicture", "event_pictures_EUROPEAN"),
    ("PRAYING_eventPicture", "event_pictures_EUROPEAN"),
    ("REFORM_eventPicture", "event_pictures_EUROPEAN"),
    ("RELIGION_eventPicture", "event_pictures_EUROPEAN"),
    ("RELIGIOUS_CONVERSION_eventPicture", "event_pictures_EUROPEAN"),
    ("RELIGIOUS_TURMOIL_eventPicture", "event_pictures_EUROPEAN"),
    ("RELIGIOUS_WARS_eventPicture", "event_pictures_EUROPEAN"),
    ("REVOLUTION_eventPicture", "event_pictures_EUROPEAN"),
    ("SHIP_SAILING_eventPicture", "event_pictures_EUROPEAN"),
    ("SIEGE_eventPicture", "event_pictures_EUROPEAN"),
    ("SPY_eventPicture", "event_pictures_EUROPEAN"),
    ("ST_PETERS_CHURCH_eventPicture", "event_pictures_EUROPEAN"),
    ("STREET_SPEECH_eventPicture", "event_pictures_EUROPEAN"),
    ("THEATRE_eventPicture", "event_pictures_EUROPEAN"),
    ("TOURNAMENT_eventPicture", "event_pictures_EUROPEAN"),
    ("TRADEGOODS_eventPicture", "event_pictures_EUROPEAN"),
    ("UNIVERSITY_eventPicture", "event_pictures_EUROPEAN"),
    ("WAR_OF_THE_ROSES_eventPicture", "event_pictures_EUROPEAN"),
    ("WESTERNISATION_eventPicture", "event_pictures_EUROPEAN"),
    ("WOUNDED_SOLDIERS_eventPicture", "event_pictures_EUROPEAN"),
    ("AULIC_COUNCIL_eventPicture", "event_pictures_AOW"),
    ("CATHOLIC_RULERS_PRAYING_eventPicture", "event_pictures_AOW"),
    ("DEFENESTRATION_PRAGUE_eventPicture", "event_pictures_AOW"),
    ("DIPLOMACY_SIGNING_eventPicture", "event_pictures_AOW"),
    ("FARMING_WIFE_eventPicture", "event_pictures_AOW"),
    ("GENERALS_DISCUSSING_eventPicture", "event_pictures_AOW"),
    ("PEASANTS_BARTERING_eventPicture", "event_pictures_AOW"),
    ("PRINCE_BISHOP_RESIGN_eventPicture", "event_pictures_AOW"),
    ("PROTESTANT_CATHOLIC_DEBATE_eventPicture", "event_pictures_AOW"),
    ("REVOLT_HUNGARIAN_eventPicture", "event_pictures_AOW"),
    ("SCOTTISH_MERCENARIES_eventPicture", "event_pictures_AOW"),
    ("SIEGE_PRAGUE_CASTLE_eventPicture", "event_pictures_AOW"),
    ("SOLDIERS_FREEZING_eventPicture", "event_pictures_AOW"),
    ("VILLAGE_BURNING_eventPicture", "event_pictures_AOW"),
    ("VILLAGE_RAIDED_eventPicture", "event_pictures_AOW"),
    ("EP_ISLAND_eventPicture", "event_pictures_ep"),
    ("EP_POLYNESIAN_MARAE_eventPicture", "event_pictures_ep"),
    ("EP_MANIHOLE_HELMET_eventPicture", "event_pictures_ep"),
    ("EP_MAORI_HAKA_eventPicture", "event_pictures_ep"),
    ("EP_MOAIS_eventPicture", "event_pictures_ep"),
    ("EP_POLYNESIAN_DANCES_eventPicture", "event_pictures_ep"),
    ("EP_POLYNESIAN_HORN_eventPicture", "event_pictures_ep"),
    ("EP_POLYNESIAN_SHIPS_eventPicture", "event_pictures_ep"),
    ("EP_POLYNESIAN_TATTOO_eventPicture", "event_pictures_ep"),
    ("EP_SAMOAN_WARRIORS_eventPicture", "event_pictures_ep"),
    ("NUSANTARA_QUEEN_eventPicture", "event_pictures_leviathan"),
    ("MALAYAN_PORT_eventPicture", "event_pictures_leviathan"),
    ("NUSANTARA_THRONE_eventPicture", "event_pictures_leviathan"),
    ("NUSANTARA_WAR_eventPicture", "event_pictures_leviathan"),
    ("SHWEDAGON_PAGON_eventPicture", "event_pictures_leviathan"),
    ("CONSTANTINOPLE_eventPicture", "event_pictures_king_of_kings"),
    ("GHULAMS_ESTATE_DEMANDS_eventPicture", "event_pictures_king_of_kings"),
    ("GHULAMS_ESTATE_eventPicture", "event_pictures_king_of_kings"),
    ("QIZILBASH_ESTATE_DEMANDS_eventPicture", "event_pictures_king_of_kings"),
    ("QIZILBASH_ESTATE_eventPicture", "event_pictures_king_of_kings"),
    ("JURAJ_JANOSIK_eventPicture", "event_pictures_winds_of_change"),
]


def grouped() -> dict[str, list[tuple[str, str]]]:
    """카테고리 한글라벨 → [(키, 표시이름), ...]"""
    out: dict[str, list[tuple[str, str]]] = {}
    for key, folder in EVENT_PICTURES:
        label = CATEGORY_LABELS.get(folder, folder)
        display = KOREAN_ALIASES.get(key)
        display = f"{display} ({key})" if display else key
        out.setdefault(label, []).append((key, display))
    return out


def folder_for(key: str) -> str | None:
    for k, folder in EVENT_PICTURES:
        if k == key:
            return folder
    return None
